import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import NextProgress from "@/components/NextProgress";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";
import "react-toastify/dist/ReactToastify.css";
import NextProgress from "@/components/NextProgress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <Suspense>
          <NextProgress />
          {children}
        </Suspense>
      </body>
    </html>
  );
}
